services:
    app:

        build:

            context: .

            dockerfile: Dockerfile

        ports:

            - "8080:80"

        volumes:

            - .:/var/www/html

        depends_on:

            - db

        networks:

            - laravel-network

    db:

        image: mysql:8.0

        environment:

            MYSQL_ROOT_PASSWORD: secret

            MYSQL_DATABASE: laravel

            MYSQL_USER: laravel

            MYSQL_PASSWORD: secret

        volumes:

            - mysql-data:/var/lib/mysql

        networks:

            - laravel-network

    phpmyadmin:

        image: phpmyadmin/phpmyadmin

        environment:

            PMA_HOST: db

        ports:

            - "8081:80"

        depends_on:

            - db

        networks:

            - laravel-network

volumes:
    mysql-data:

networks:
    laravel-network:

